spring.application.name=student_sanagement_system
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost/Student_Management_System
spring.datasource.username=root
spring.datasource.password=Sasi@416
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true